name: em_chat_uikit
description: A set of ui components adapted to the chat sdk can quickly build a chat page
  and chat through the chat sdk by invoking the ui components.
version: 2.1.0+1
homepage: https://www.easemob.com/

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter

  im_flutter_sdk: 4.8.2



  
#  record: 5.1.2  # oh无 换 flutter_sound
  flutter_sound:
    git:
      url: "https://gitee.com/openharmony-sig/flutter_sound.git"
      path: "flutter_sound"
# flutter_sound需要获取录音权限
  permission_handler:
    git:
      url: "https://gitee.com/openharmony-sig/flutter_permission_handler.git"
      path: "permission_handler"

  shared_preferences: 2.2.3

  chat_uikit_theme: 1.0.4

#  path_provider: 2.1.4 暂时用不到

#  file_picker: 8.0.5  #oh无 换 file_selector
  file_selector:
    git:
      url: "https://gitee.com/openharmony-sig/flutter_packages.git"
      path: "packages/file_selector/file_selector"

#  audioplayers: 6.0.0
  audioplayers:
    git:
      url: "https://gitee.com/openharmony-sig/flutter_audioplayers.git"
      path: "packages/audioplayers"

#  image_picker: 1.1.2
  image_picker:
    git:
      url: "https://gitee.com/openharmony-sig/flutter_packages.git"
      path: "packages/image_picker/image_picker"

#  video_thumbnail: 0.5.3  #oh无 换 video_compress
  video_compress:
    git:
      url: "https://gitee.com/openharmony-sig/fluttertpc_video_compress.git"
      ref: master
#  export_video_frame:
#    git:
#      url: "https://gitee.com/openharmony-sig/fluttertpc_export_video_frame.git"
#      ref: master

#  video_player: 2.8.1
  video_player:
    git:
      url: "https://gitee.com/openharmony-sig/flutter_packages.git"
      path: "packages/video_player/video_player"

  flutter_localization: 0.2.0

  scroll_to_index: ^3.0.1  #oh无

#  cached_network_image: 3.3.0
#  cached_network_image: 3.1.0+1  #oh

  chat_uikit_keyboard_panel: 0.1.1

  html: ^0.15.4  #oh无

# 强制使用版本
dependency_overrides:
  shared_preferences:
    git:
      url: "https://gitee.com/openharmony-sig/flutter_packages.git"
      path: "packages/shared_preferences/shared_preferences"

  flutter_localization: 0.1.14



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  plugin:
    platforms:
      android:
        package: com.ease.em_chat_uikit
        pluginClass: EmChatUikitPlugin
      ios:
        pluginClass: EmChatUikitPlugin

  assets:
    - assets/images/
    - assets/images/emojis/