name: em_chat_uikit
description: A set of ui components adapted to the chat sdk can quickly build a chat page
  and chat through the chat sdk by invoking the ui components.
version: 2.2.0
homepage: https://www.easemob.com/

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

  im_flutter_sdk: 4.13.0
  
  record: 5.1.2

  shared_preferences: 2.2.3

  # chat_uikit_theme: 1.0.4
  chat_uikit_theme:
    path: ../chat_uikit_theme

  path_provider: 2.1.4

  file_picker: 8.3.2

  audioplayers: 6.0.0

  image_picker: 1.1.2

  video_compress: 3.1.4

  video_player: 2.9.5

  flutter_localization: 0.2.0

  scroll_to_index: ^3.0.1

  cached_network_image: 3.3.1

  # chat_uikit_keyboard_panel: 0.1.1
  chat_uikit_keyboard_panel:
    path: ../chat_uikit_keyboard_panel

  html: ^0.15.4

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.ease.em_chat_uikit
        pluginClass: EmChatUikitPlugin
      ios:
        pluginClass: EmChatUikitPlugin

  assets:
    - assets/images/
    - assets/images/emojis/
